### ISSUE TITLE
Token Transfer Contract Spec

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/zeneth#1]
Using a contract will allow us to make the tx atomic, which should provide a bit of protection from uncle leak attacks of any kind.

Possible function signature:

```solidity
function transferAndBribe(address _token, uint256 _tokenAmount, address _receiver, uint256 _ethBribe);
```

Possible function state vars:

* `uint256 fee`
* `address owner`

Function logic:

* Perform `transferFrom` of `_tokenAmount` of `_token` (implies pre-approval)
* Swap tokens for exact eth amount `_ethBribe + fee` (via uniswap v2 router)
* `transfer` amount of `fee` to `owner`
* `transfer` amount of `_ethBribe` to coinbase
* ERC20 `transfer` remaining tokens to `_receiver`

Overall this would only need 2 txs, right?

1) Approval
2) `transferAndBribe` function call

Other thoughts/questions

* Presumably `owner` should be able to update `fee`
* OR should `fee` somehow be dynamic, calculated as percentage of send, etc...?
* Can the function find the uniswap path internally, or assume/calculate a token/ETH pair, or does the path for the swap also need to be part of the function signature?
* Any other approaches that might be more gas efficient?
* Any security concerns, loss of fund risks? Rebasing tokens? Etcc..?

**Comment by wildmolasses** [comment]
step 1: whatever user wants to do gaslessly (deposit into L2, or interact with compound, etc)
- wont have eth to pay gas, wants to do it via flashbots
- if able to send 0 gas price tx, they dont need eth
- call any action on any protocol supported by frontend

step 2: transfer tokens to scopelift as relayer fee
- we are relayer. user pays relayer for operating cost (DAI, ~ETH~, etc)
- scopelift: "hey flashbots we have a bundle"

step 3: scopelift transfers eth to miner (either comes from user in step 2, or token swap)
- take DAI from user, swap to ETH, transfer to miner
- Could optionally involve treasury (e.g. dont have to swap if we already have enough ETH)

our contract is step 2 and 3 for any step 1

other example:
user has 10000 DAI but no ETH
wants to move it into compound

step 1:
- precalculate how much DAI we need for swap / bribe, subtract that from input into compound. help user compose tx.
soon flashbots won't accept bundles that have a revert (e.g. if they deposit 10000 DAI into compound, and then give us 10 DAI for bribe/fee, flashbots won't accept it)
- "OK you can deposit up to 99900 DAI into compound, and your bribe fee is 100 DAI"
- we can't know exact on both sides -- do we have to know exactly how much ETH we need and use swapTokensForExactETH or is it implicit?

amount of bribe is variable so we think implicit

strategies: 

- 1. if user gives us 100 DAI and that's not enough for the flashbots to include it in a block, then we could compose our swap
- 2. another option is like maximillion contract where we refund difference between our swap and the miner fee

preferring option 1 atm.

for now, let's start with erc20 interface and l2 deposit into protocols x, y, z. for now, hardcoded specific functionality. over time, add more protocols / features. could take inspiration from defisaver or instadapp. be very careful about expanding scope!!

----

maybe later, to generalize, would need to support "paste your abi" interface, and then estimate gas (or instead of estimating gas, just pull miner fees from api and try those)

for v2, we could also split up where tokens are going. we could do multiple things, almost like a shopping cart / checkout composition thing

![Screen Shot 2021-04-20 at 3 09 36 PM](https://user-images.githubusercontent.com/5423313/115457661-70186c00-a1ea-11eb-99c7-6e1cda392b27.png)
